---
- hosts: all
  sudo: yes
  gather_facts: yes

  tasks:
    - name: Ensure apt cache is updated.
      apt: update_cache=yes cache_valid_time=3600

    - name: Configure SSH daemon.
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { regexp: '^UseDNS', line: 'UseDNS no' }
        - { regexp: '^GSSAPIAuthentication', line: 'GSSAPIAuthentication no' }

    # Vagrant SSH configuration.
    - name: Configure Vagrant .ssh directory.
      file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        group: vagrant
        mode: 0700

    - name: Get Vagrant's public key.
      get_url:
        url: https://github.com/mitchellh/vagrant/raw/master/keys/vagrant.pub
        dest: /home/vagrant/.ssh/authorized_keys
        owner: vagrant
        group: vagrant
        mode: 0600

    - apt: "name={{ item }} state=installed"
      with_items:
        - git
        - wget
        - curl
        - vim
        - mc
        - htop
        - iotop
        - nfs-common

    - apt: "pkg={{ item }} state=absent"
      with_items:
        - ppp
        - pppconfig
        - pppoeconf
        - cpp
        - gcc
        - g++
        - libx11-data
        - xauth
        - libxmuu1
        - libxcb1
        - libx11-6
        - libxext6
        - linux-source
