---
- hosts: all
  sudo: yes
  gather_facts: yes

  tasks:
    - include: vagrant.yml

    - apt: "name={{ item }} state=installed"
      with_items:
        - git
        - wget
        - curl
        - vim
        - mc
        - htop
        - iotop
        - nfs-common
